### ISSUE TITLE
Add optional support for using sanitizers

### ISSUE THREAD

**Issue by EinarElen** [LDMX-Software/cmake#14]
See https://github.com/LDMX-Software/ldmx-sw/issues/1043 for details. 

This adds a new CMake script which adds options for turning on one or more of the sanitizer instrumentation tools. Each sanitizer gets turned into an option (all default to off) that can be turned on during the cmake step of building LDMX-sw. You enable sanitizers for a project with the `enable_sanitizers` function, which we make use of in the `setup_library` function in `BuildMacros.cmake`. 

The code is taken from https://github.com/cpp-best-practices/cpp_starter_project (for a demo, see https://youtu.be/YbgH7yat-Jo?t=805).

**Comment by tomeichlersmith** [comment]
I think this was resolved by #15 feel free to re-open if that wasn't the case.
